# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scale.cpp <- function(X) {
    .Call(`_dummyscoring_scale`, X)
}

sparse.cor <- function(X, Y=X) {
    .Call(`_dummyscoring_sparsecor`, X, Y)
}

score.matrix <- function(X, P, Uinv, R, method, nthreads, showprogress) {
    .Call(`_dummyscoring_score_matrix`, X, P, Uinv, R, method, nthreads, showprogress)
}

dummy.extension <- function(X, X_v, P_vf, R_vv) {
    .Call(`_dummyscoring_dummy_extension`, X, X_v, P_vf, R_vv)
}

